--- TAO SCHEMA USER 
CREATE USER C##SCHEMA_USER;
GRANT CREATE ANY TABLE TO C##SCHEMA_USER;
GRANT SELECT, UPDATE, INSERT, DELETE ON USERS TO C##SCHEMA_USER;
ALTER USER C##SCHEMA_USER QUOTA UNLIMITED ON USERS;



--- TAO TAI KHOAN NGUOI DUNG
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER HOANGVU IDENTIFIED BY 1234;
GRANT CREATE SESSION TO HOANGVU;


---- CAP QUYEN S, U , I  
GRANT SELECT ON C##SCHEMA_USER.LOAIPHONG TO HOANGVU;
GRANT INSERT ON C##SCHEMA_USER.PHIEUDANGKY TO HOANGVU;
GRANT INSERT ON C##SCHEMA_USER.PHIEUDANGKYCT TO HOANGVU;
GRANT SELECT ON C##SCHEMA_USER.DSSANPHAM_DV TO HOANGVU;
GRANT SELECT, INSERT ON C##SCHEMA_USER.PHIEUDKSPDV TO HOANGVU;
GRANT INSERT ON C##SCHEMA_USER.PHIEUCHITIETSP_DV TO HOANGVU;
GRANT SELECT ON C##SCHEMA_USER.DANHSACHTOUR TO HOANGVU;
GRANT INSERT ON C##SCHEMA_USER.DANGKYTOUR TO HOANGVU;
GRANT INSERT ON C##SCHEMA_USER.DANHSACHTHAMGIATOUR TO HOANGVU;
GRANT INSERT ON C##SCHEMA_USER.DANGKYTOURCHITIET TO HOANGVU;

--- QUYEN EXECUTE PROCEDURE
GRANT SELECT ON C##SCHEMA_USER.PHIEUDANGKY TO HOANGVU;
GRANT EXECUTE ON CreateNewMaPhieuDK TO HOANGVU;
GRANT EXECUTE ON GENERATE_PHIEU_ID TO HOANGVU;
GRANT EXECUTE ON GENERATE_PHIEUTOUR_ID TO HOANGVU;