
---- TAO BANG TAI KHOAN
CREATE TABLE C##SCHEMA_USER.TAIKHOAN
(
    USERNAME varchar2(30),
    MATKHAU varchar2(30),
    LOAITK int default(0),
    PRIMARY KEY(USERNAME)
)


--- DONVILUUHANH
CREATE TABLE C##SCHEMA_USER.DONVILUHANH
(
    MADONVI NUMBER GENERATED ALWAYS as IDENTITY(START WITH 1 INCREMENT by 1),
    TEN NVARCHAR2(50),
    PRIMARY KEY(MADONVI)
)

---- DANH SACH TOUR
CREATE TABLE C##SCHEMA_USER.DANHSACHTOUR
(
    MATOUR VARCHAR2(4) ,
    TEN NVARCHAR2(50),
    GIATIEN NUMBER(10,2),
    MACONGTY INT, 
    MOTA NVARCHAR2(200),
    TINHTRANG NVARCHAR2(100),
    
    PRIMARY KEY(MATOUR)
)
/
---- PHIEU DANG KY TOUR
CREATE TABLE C##SCHEMA_USER.DANGKYTOUR
(
    MAPHIEUTOUR VARCHAR2(4),
    TONGNGUOI INT DEFAULT(0),
    TOSOLUONGTOUR INT DEFAULT(0),
    TONGTIEN NUMBER(10,2), 
    TUTUC INT DEFAULT(0),
    MAPHIEUDK VARCHAR2(4),
    PRIMARY KEY(MAPHIEUTOUR)
)
ALTER TABLE C##SCHEMA_USER.DANGKYTOUR ADD THOIGIANDK VARCHAR2(30);
/
--- PHIEU DANG KY TOUR CHI TIET
CREATE TABLE C##SCHEMA_USER.DANGKYTOURCHITIET
(
    MAPHIEUTOUR VARCHAR2(4),
    MATOUR VARCHAR2(4),
    PRIMARY KEY(MAPHIEUTOUR, MATOUR)
)

/
--- PHIEU DANG KY
CREATE TABLE C##SCHEMA_USER.PHIEUDANGKY
(
    MAPHIEUDK VARCHAR2(4),
    TENNGUOIDK NVARCHAR2(50),
    SODT VARCHAR2(11),
    EMAIL VARCHAR2(25),
    NGAYCHECKIN DATE,
    NGAYCHECKOUT DATE, 
    TONGPHONG INT DEFAULT(0),
    YEUCAUDB NVARCHAR2(200),
    TONGTIEN NUMBER(10, 4),
    DATHANHTOAN NUMBER(10, 4),
    NGAYLAP DATE, 
    VANCHUYENHL INT DEFAULT(0),
    PRIMARY KEY(MAPHIEUDK)
)
/
-- Doi kieu DL
ALTER TABLE C##SCHEMA_USER.PHIEUDANGKY
MODIFY(
    NGAYCHECKIN VARCHAR2(30),
    NGAYCHECKOUT VARCHAR2(30),
    NGAYLAP VARCHAR2(30)
)
/
--- PHIEU DANG KY CHI TIET
CREATE TABLE C##SCHEMA_USER.PHIEUDANGKYCT
(
    MAPHIEUDK VARCHAR2(4),
    STT INT DEFAULT(1),
    LOAIPHONG VARCHAR2(4), 
    SOLUONG INT DEFAULT(0),
    GIATIEN NUMBER(10,4),
    
    PRIMARY KEY(MAPHIEUDK, STT)
)

/
--- LOAIPHONG
CREATE TABLE  C##SCHEMA_USER.LOAIPHONG
(
    MALOAI VARCHAR2(4), 
    TENLOAI NVARCHAR2(50),
    SONGUOI INT,
    TONGPHONG INT,
    PHONGCON INT,
    GIATIEN NUMBER(10,4),
    PRIMARY KEY(MALOAI)
)


/
--- DANH SACH PHONG
CREATE TABLE C##SCHEMA_USER.DANHSACHPHONG
(
    MAPHONG VARCHAR2(4),
    LOAIPHONG VARCHAR2(4),
    TINHTRANG NVARCHAR2(25),
    
    PRIMARY KEY(MAPHONG)
)
/
-- DSSANPHAM_DV 

CREATE TABLE C##SCHEMA_USER.DSSANPHAM_DV
(
    MASPDV VARCHAR2(4),
    TEN NVARCHAR2(50),
    GIATIEN NUMBER(10,4),
    SONGUOIDUNG INT,
    MOTA NVARCHAR2(200),
    DANHGIA INT,
    TINHTRANG NVARCHAR2(25),
    
    PRIMARY KEY(MASPDV)
)

-- PHIEUDANGKYSPDV
CREATE TABLE C##SCHEMA_USER.PHIEUDKSPDV
(
    MAPHIEU VARCHAR2(4),
    MAPHIEUDK VARCHAR2(4), 
    TONGSL INT, 
    TONGTIEN NUMBER(10,4),
    
    PRIMARY KEY(MAPHIEU)
)
/

-- PHIEUDANGKYSPDVCT
CREATE TABLE C##SCHEMA_USER.PHIEUCHITIETSP_DV
(
    MAPHIEU VARCHAR2(4),
    MASPDV VARCHAR2(4),
    SOLUONG INT, 
    GIATIEN NUMBER(10,4),
    
    PRIMARY KEY(MAPHIEU, MASPDV)
)
/
-- SPDVCUNGCAP
CREATE TABLE C##SCHEMA_USER.SPDVCUNGCAP
( 
    MASPDV VARCHAR2(4),
    MALOAI VARCHAR2(4), 
    
    PRIMARY KEY(MASPDV, MALOAI)
)
/
-- HO SO THANH TOAN
CREATE TABLE C##SCHEMA_USER.HOSOTHANHTOAN
(
    MAHOSO VARCHAR2(4),
    TENKHACHHANG NVARCHAR2(50),
    CMND VARCHAR2(11),
    SDT  VARCHAR2(11),
    STK VARCHAR2(11),
    MAPHIEUDK VARCHAR2(4),
    PRIMARY KEY(MAHOSO)
)
ALTER TABLE C##SCHEMA_USER.HOSOTHANHTOAN
ADD PHUONGTHUC VARCHAR2(25);

/
-- HOA DON
CREATE TABLE C##SCHEMA_USER.HOADON
(
    MAHOSO VARCHAR2(4),
    STT INT,
    TONGTIEN NUMBER(10,4),
    
    PRIMARY KEY(MAHOSO, STT)
)
-- DANH SACH DANG KY TOUR
CREATE TABLE C##SCHEMA_USER.DANHSACHTHAMGIATOUR
(
    MATOUR VARCHAR2(4),
    STT INT, 
    HOTEN NVARCHAR2(50), 
    CMND VARCHAR2(11),
    
    PRIMARY KEY(MATOUR, STT)
)

-- KHOA NGOAI FOREIGN KEY

-- DANH SACH TOUR
ALTER TABLE C##SCHEMA_USER.DANHSACHTOUR ADD CONSTRAINT FK_DSTOUR_DONVILUHANH FOREIGN KEY(MACONGTY) REFERENCES C##SCHEMA_USER.DONVILUHANH(MADONVI);


-- PHIEU DANG KY TOUR CHI TIET
ALTER TABLE C##SCHEMA_USER.DANGKYTOURCHITIET ADD CONSTRAINT FK_TOURCT_DSTOUR FOREIGN KEY(MATOUR) REFERENCES C##SCHEMA_USER.DANHSACHTOUR(MATOUR);
ALTER TABLE C##SCHEMA_USER.DANGKYTOURCHITIET ADD CONSTRAINT FK_TOURCT_DKTOUR FOREIGN KEY(MAPHIEUTOUR) REFERENCES C##SCHEMA_USER.DANGKYTOUR(MAPHIEUTOUR);


-- PHIEU DANG KY TOUR
ALTER TABLE C##SCHEMA_USER.DANGKYTOUR ADD CONSTRAINT FK_DKTOUR_PHIEUDK FOREIGN KEY(MAPHIEUDK) REFERENCES C##SCHEMA_USER.PHIEUDANGKY(MAPHIEUDK);


-- PHIEU DANG KY CHI TIET
ALTER TABLE C##SCHEMA_USER.PHIEUDANGKYCT ADD CONSTRAINT FK_PHIEUDKCT_PHIEUDK FOREIGN KEY(MAPHIEUDK) REFERENCES C##SCHEMA_USER.PHIEUDANGKY(MAPHIEUDK);
ALTER TABLE C##SCHEMA_USER.PHIEUDANGKYCT ADD CONSTRAINT FK_PHIEUDKCT_LOAIPHONG FOREIGN KEY(LOAIPHONG) REFERENCES C##SCHEMA_USER.LOAIPHONG(MALOAI);

-- DANH SACH PHONG
ALTER TABLE C##SCHEMA_USER.DANHSACHPHONG ADD CONSTRAINT FK_DANHSACHPHONG_LOAIPHONG FOREIGN KEY(LOAIPHONG) REFERENCES C##SCHEMA_USER.LOAIPHONG(MALOAI);

-- PHIEUDANGKYSPDV
ALTER TABLE C##SCHEMA_USER.PHIEUDKSPDV ADD CONSTRAINT FK_PHIEUDKSPDV_PHIEUDK FOREIGN KEY(MAPHIEUDK) REFERENCES C##SCHEMA_USER.PHIEUDANGKY(MAPHIEUDK);

-- PHIEUDANGKYSPDVCT
ALTER TABLE C##SCHEMA_USER.PHIEUCHITIETSP_DV ADD CONSTRAINT FK_PHIEUCTSPDV_PHIEUDKSPDV FOREIGN KEY(MAPHIEU) REFERENCES  C##SCHEMA_USER.PHIEUDKSPDV(MAPHIEU);
ALTER TABLE C##SCHEMA_USER.PHIEUCHITIETSP_DV ADD CONSTRAINT FK_PHIEUCTSPDV_SPDV FOREIGN KEY(MASPDV) REFERENCES C##SCHEMA_USER.DSSANPHAM_DV(MASPDV);

-- SPDVCUNGCAP
ALTER TABLE C##SCHEMA_USER.SPDVCUNGCAP ADD CONSTRAINT FK_SPDVCUNGCAP_LOAIPHONG FOREIGN KEY(MALOAI) REFERENCES C##SCHEMA_USER.LOAIPHONG(MALOAI);

-- HO SO THANH TOAN
ALTER TABLE C##SCHEMA_USER.HOSOTHANHTOAN ADD CONSTRAINT FK_HOSOTHANHTOAN_PHIEUDANGKY FOREIGN KEY(MAPHIEUDK) REFERENCES C##SCHEMA_USER.PHIEUDANGKY(MAPHIEUDK);

-- HOA DON
ALTER TABLE C##SCHEMA_USER.HOADON ADD CONSTRAINT FK_HOADON_HOSOTHANHTOAN FOREIGN KEY(MAHOSO) REFERENCES C##SCHEMA_USER.HOSOTHANHTOAN(MAHOSO);

-- DANH SACH THAM GIA TOUR
ALTER TABLE C##SCHEMA_USER.DANHSACHTHAMGIATOUR ADD CONSTRAINT FK_DANHSACHTHAMGIATOUR_DANGKYTOUR FOREIGN KEY(MATOUR) REFERENCES C##SCHEMA_USER.DANGKYTOUR(MAPHIEUTOUR);