-- DU LIEU CHO BANG TAI KHOAN
INSERT INTO C##SCHEMA_USER.TAIKHOAN VALUES('HOANGVU', '1234', 0);



INSERT INTO C##SCHEMA_USER.LOAIPHONG(MALOAI, TENLOAI, SONGUOI, TONGPHONG, PHONGCON, GIATIEN)
VALUES ('DLX', 'Deluxe', 3, 10, 5, 1500);
INSERT INTO C##SCHEMA_USER.LOAIPHONG(MALOAI, TENLOAI, SONGUOI, TONGPHONG, PHONGCON, GIATIEN)
VALUES ('SUP', 'Superior', 2, 20, 10, 1000);
INSERT INTO C##SCHEMA_USER.LOAIPHONG(MALOAI, TENLOAI, SONGUOI, TONGPHONG, PHONGCON, GIATIEN)
VALUES ('FAM', 'Family', 4, 5, 3, 2000);
INSERT INTO C##SCHEMA_USER.LOAIPHONG(MALOAI, TENLOAI, SONGUOI, TONGPHONG, PHONGCON, GIATIEN)
VALUES ('STD', 'Standard', 2, 30, 15, 7000);

INSERT INTO C##SCHEMA_USER.DSSANPHAM_DV(MASPDV, TEN, GIATIEN, SONGUOIDUNG, MOTA, DANHGIA, TINHTRANG)
VALUES ('DV01', N'Travel Insurance', 25.99, 1, N'Protect your trip and your peace of mind with travel insurance', 4, N'Active');

INSERT INTO C##SCHEMA_USER.DSSANPHAM_DV(MASPDV, TEN, GIATIEN, SONGUOIDUNG, MOTA, DANHGIA, TINHTRANG)
VALUES ('DV02', N'Airport Transfer', 10.50, 1, N'Enjoy a hassle-free ride from airport to hotel', 5, N'Active');

INSERT INTO C##SCHEMA_USER.DSSANPHAM_DV(MASPDV, TEN, GIATIEN, SONGUOIDUNG, MOTA, DANHGIA, TINHTRANG)
VALUES ('DV03', N'Spa Treatment', 50.00, 1, N'Relax and pamper yourself with our spa services', 3, N'Active');

INSERT INTO C##SCHEMA_USER.DSSANPHAM_DV(MASPDV, TEN, GIATIEN, SONGUOIDUNG, MOTA, DANHGIA, TINHTRANG)
VALUES ('DV04', N'Rental Car', 35.75, 1, N'Explore the city at your own pace with a rental car', 4, N'Active');



INSERT INTO C##SCHEMA_USER.DONVILUHANH (TEN) VALUES ('Vietnam Airlines');
INSERT INTO C##SCHEMA_USER.DONVILUHANH (TEN) VALUES ('Jetstar Pacific');
INSERT INTO C##SCHEMA_USER.DONVILUHANH (TEN) VALUES ('Vietjet Air');
INSERT INTO C##SCHEMA_USER.DONVILUHANH (TEN) VALUES ('Bamboo Airways');


INSERT INTO C##SCHEMA_USER.DANHSACHTOUR (MATOUR, TEN, GIATIEN , MACONGTY, MOTA, TINHTRANG) VALUES ('T1', 'Tour du l?ch Nha Trang', 100.000, 1, N'Tour du l?ch 4 ngày 3 ?êm Nha Trang', N'?ã bán');
INSERT INTO C##SCHEMA_USER.DANHSACHTOUR (MATOUR, TEN, GIATIEN , MACONGTY, MOTA, TINHTRANG) VALUES ('T2', 'Tour du l?ch ?à N?ng', 200.000, 2, N'Tour du l?ch 5 ngày 4 ?êm ?à N?ng', N'Còn hàng');
INSERT INTO C##SCHEMA_USER.DANHSACHTOUR (MATOUR, TEN, GIATIEN , MACONGTY, MOTA, TINHTRANG) VALUES ('T3', 'Tour du l?ch Phú Qu?c', 300.000, 3, N'Tour du l?ch 6 ngày 5 ?êm Phú Qu?c', N'?ã bán');
INSERT INTO C##SCHEMA_USER.DANHSACHTOUR (MATOUR, TEN, GIATIEN , MACONGTY, MOTA, TINHTRANG) VALUES ('T4', 'Tour du l?ch Sapa', 400.000, 4, N'Tour du l?ch 7 ngày 6 ?êm Sapa', N'Còn hàng');
